# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgMainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgMain(object):
    def setupUi(self, dlgMain):
        dlgMain.setObjectName("dlgMain")
        dlgMain.resize(370, 106)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/connected.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dlgMain.setWindowIcon(icon)
        self.actQuitApp = QtWidgets.QAction(dlgMain)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actQuitApp.setIcon(icon1)
        self.actQuitApp.setObjectName("actQuitApp")
        self.actAbout = QtWidgets.QAction(dlgMain)
        self.actAbout.setCheckable(False)
        self.actAbout.setChecked(False)
        self.actAbout.setIcon(icon)
        self.actAbout.setObjectName("actAbout")
        self.actAboutQt = QtWidgets.QAction(dlgMain)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Qt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actAboutQt.setIcon(icon2)
        self.actAboutQt.setObjectName("actAboutQt")
        self.actStartWithSystem = QtWidgets.QAction(dlgMain)
        self.actStartWithSystem.setCheckable(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/start_with_system.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actStartWithSystem.setIcon(icon3)
        self.actStartWithSystem.setObjectName("actStartWithSystem")

        self.retranslateUi(dlgMain)
        QtCore.QMetaObject.connectSlotsByName(dlgMain)

    def retranslateUi(self, dlgMain):
        _translate = QtCore.QCoreApplication.translate
        dlgMain.setWindowTitle(_translate("dlgMain", "Check Internet Connection"))
        self.actQuitApp.setText(_translate("dlgMain", "Quit"))
        self.actQuitApp.setToolTip(_translate("dlgMain", "Quit"))
        self.actAbout.setText(_translate("dlgMain", "About Program"))
        self.actAbout.setToolTip(_translate("dlgMain", "About Program"))
        self.actAboutQt.setText(_translate("dlgMain", "About Qt"))
        self.actAboutQt.setToolTip(_translate("dlgMain", "About Qt"))
        self.actStartWithSystem.setText(_translate("dlgMain", "Start with system"))
        self.actStartWithSystem.setToolTip(_translate("dlgMain", "Start with system"))
import res_rc
